apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
        - name: rag-backend
          image: rag-backend:latest
          ports:
            - containerPort: 8000

