apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000        # Port exposé dans le cluster
      targetPort: 8000  # Port sur lequel ton container backend écoute
  type: ClusterIP