apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
        - name: rag-frontend
          image: rag-frontend:latest
          ports:
            - containerPort: 8501
