apiVersion: v1
kind: Service
metadata:
  name: rag-frontend-service
spec:
  selector:
    app: frontend          # DOIT matcher le label du deployment frontend
  ports:
    - name: http
      port: 80             # port vu par nginx ingress
      targetPort: 8501     # port du container streamlit
  type: ClusterIP
