apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-storage
  template:
    metadata:
      labels:
        app: rag-storage
    spec:
      containers:
      - name: rag-storage
        image: lseillier/rag-storage:v2
        ports:
          - containerPort: 9000

